use find_college_db;
DELETE  FROM LOGIN_STUDENTS;
ALTER TABLE LOGIN_STUDENTS AUTO_INCREMENT = 1;
INSERT INTO LOGIN_STUDENTS(EMAIL,PASSWRD) VALUES("mayankanuragi2013@gmail.com","pass");
INSERT INTO LOGIN_STUDENTS(EMAIL,PASSWRD) VALUES("rakshitnaik79@gmail.com","pass");
INSERT INTO LOGIN_STUDENTS(EMAIL,PASSWRD) VALUES("manojgalanki@gmail.com","pass");
#SELECT * from LOGIN_STUDENTS;
